"""
AI Logic - Member B
Story generation using K2 Think & Gemini
"""
import os
from typing import Optional
import google.generativeai as genai


# Gemini configuration
genai.configure(api_key=os.getenv("GEMINI_API_KEY"))


async def generate_story_with_k2(prompt: str, style: str) -> str:
    """
    Generate story using K2 Think
    TODO: K2 Think API integration required
    """
    # K2 Think API call logic
    # Currently placeholder
    return f"[Story draft generated by K2 Think]\nPrompt: {prompt}\nStyle: {style}"


async def enhance_story_with_gemini(draft_story: str) -> str:
    """
    Enhance and refine story using Gemini
    """
    try:
        model = genai.GenerativeModel('gemini-pro')
        
        prompt = f"""
Please enhance the following story draft to make it more engaging and vivid.
- Use language that children can easily understand
- Include emotionally rich expressions
- Add visual descriptions that help imagine the scenes

Draft:
{draft_story}

Enhanced Story:
"""
        
        response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        print(f"Gemini error: {e}")
        return draft_story


async def generate_story_text(prompt: str, style: str = "fantasy") -> str:
    """
    Complete story generation pipeline
    1. Generate draft with K2 Think
    2. Enhance with Gemini
    """
    # Generate draft with K2 Think
    draft = await generate_story_with_k2(prompt, style)
    
    # Enhance with Gemini
    enhanced_story = await enhance_story_with_gemini(draft)
    
    return enhanced_story


async def split_story_into_scenes(story: str, num_scenes: int = 4) -> list[str]:
    """
    Split story into scenes (for image generation)
    """
    model = genai.GenerativeModel('gemini-pro')
    
    prompt = f"""
Please split the following story into {num_scenes} visual scenes.
Each scene should include specific visual elements suitable for image generation.

Story:
{story}

Format: Output each scene as "Scene X: [description]"
"""
    
    try:
        response = model.generate_content(prompt)
        scenes = response.text.strip().split('\n')
        return [scene.strip() for scene in scenes if scene.strip()]
    except Exception as e:
        print(f"Scene splitting error: {e}")
        # Default split
        return [story]
